#sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t sathish1983/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sathish1983/multi-docker-client-test npm run test

after_success:
    - docker build -t sathish1983/multi-docker-client ./client
    - docker build -t sathish1983/multi-docker-nginx ./nginx
    - docker build -t sathish1983/multi-docker-server ./server
    - docker build -t sathish1983/multi-docker-worker ./worker
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to docker hub
    - docker push sathish1983/multi-docker-client
    - docker push sathish1983/multi-docker-nginx
    - docker push sathish1983/multi-docker-server
    - docker push sathish1983/multi-docker-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-772900707343"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY